apiVersion: v1
kind: ConfigMap
metadata:
  name: dpn-airflow-config
  labels:
    app: dpn-airflow

data:
  AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"

  AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE: "False"

  AIRFLOW__CORE__DAGS_IGNORE_FILE_SYNTAX: "regexp"

  AIRFLOW__DATABASE__HOST: "dpn-airflow-postgres"
  AIRFLOW__DATABASE__PORT: "5432"

  AIRFLOW__CELERY__BROKER_URL: "redis://dpn-airflow-redis:6379/0"
  AIRFLOW__CELERY__BROKER_CONNECTION_RETRY_ON_STARTUP: "true"
  AIRFLOW__CELERY__WORKER_CONCURRENCY: "4"
  AIRFLOW__CELERY__TASK_TRACK_STARTED: "true"
  AIRFLOW__CELERY__WORKER_CANCEL_LONG_RUNNING_TASKS_ON_CONNECTION_LOSS: "true"

  AIRFLOW__CELERY__BROKER_TRANSPORT_OPTIONS: '{"visibility_timeout": 3600}'

  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
  AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "20"
  AIRFLOW__SCHEDULER__ZOMBIE_TASK_THRESHOLD: "300"
  AIRFLOW__SCHEDULER__DAG_FILE_PROCESSOR_TIMEOUT: "120"

  AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
  AIRFLOW__LOGGING__REMOTE_LOGGING: "False"

  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
