namespace: ns-dpn-01
name: producer-topic-schema-mapper
acrName: ""
imageName: producer-topic-schema-mapper
imageTag: ""

bootstrapServer: dpn-kafka-src:9092

# Required – must match srcTopicName configured in the adaptor
<<<<<<< HEAD
srcTopicName: dpn-producer-eq-stage
=======
srcTopicName: dpn-producer-eq-sample-1-src
>>>>>>> 64116fc5eaf0262977db8114b8f1dded39482460

# Leave blank to auto-derive:
#   mapperTopicName  →  <srcTopicName>-trfm
#   targetTopicName  →  <srcTopicName>-target
mapperTopicName: dpn-producer-eq-raw
# targetTopicName: ""

mapperGroupId: producer-topic-schema-mapper

# Metadata stamped into every outgoing message header
schemaType: eq
orgName: neso

consumerRetryDelaySecs: 5

productType: eq
SERVICE_NAME: data-pipeline
SERVICE_VERSION: 1.0.0
