namespace: ns-dpn-01
name: producer-file-adaptor
cloudProviderType: azure
acrName: ""
imageName: producer-file-adaptor-eq
imageTag: ""
productType: ""
bootstrapServer: dpn-kafka-src:9092
srcContainerName: eqbd-stage
storageConnectionSecret: producer-file-dp-secret
mapperTopicName: dpn-producer-eqbd-raw
mapperContainerName: eqbd-raw
targetTopicName: dpn-producer-eqbd-target
targetContainerName: eqbd-target
scheduleInterval: 60  # schedule interval in seconds
orgName: BP
schemaType: ""
STATSD_HOST: ''
STATSD_PORT: 8125
PIPELINE_CONTROL_TOPIC : dpn-pipeline-control
PIPELINE_STATUS_TOPIC : dpn-pipeline-status
SCHEDULER_BACKEND: kafka-trigger
EXECUTION_MODE : manual
PRODUCT_NAME : eqbd
# ------- AWS Config ------------
awsEndpointUrl: "<<your specific value>>"
awsRegion: us-east-1
awsAccessSecret: aws-access-secret
OTEL_EXPORTER_OTLP_ENDPOINT: http://dpn-otel-collector.ns-dpn-health-01.svc.cluster.local:4317
OTEL_EXPORTER_OTLP_PROTOCOL: grpc
OTEL_EXPORTER_OTLP_INSECURE: "true"
SERVICE_NAME: my-service-name
SERVICE_VERSION: 1.0.0
ENVIRONMENT: development