namespace: ns-dpn-01
name: producer-topic-schema-mapper
acrName: ""
imageName: producer-topic-schema-mapper
imageTag: ""

bootstrapServer: dpn-kafka-src:9092

# Required – must match srcTopicName configured in the adaptor
srcTopicName: dpn-producer-eqbd-stage

# Leave blank to auto-derive:
#   mapperTopicName  →  <srcTopicName>-trfm
#   targetTopicName  →  <srcTopicName>-target
mapperTopicName: dpn-producer-eqbd-raw
# targetTopicName: ""

mapperGroupId: producer-topic-schema-mapper

# Metadata stamped into every outgoing message header
schemaType: eqbd
orgName: neso

consumerRetryDelaySecs: 5

productType: eqbd
SERVICE_NAME: data-pipeline
SERVICE_VERSION: 1.0.0
