apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  selector: 
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.name }}
          #image: "{{ .Values.acrName }}.azurecr.io/dsi/{{ .Values.imageName }}:{{ .Values.imageTag }}"
          image: "{{ .Values.imageRegistry }}/{{ .Values.imageName }}:{{ .Values.imageTag }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
            runAsUser: 10000
            runAsNonRoot: true
          command: ['python', 'main.py']
          env:
          - name: "scheduleInterval"
            value: {{ .Values.scheduleInterval | quote }}
          - name: "cloudProviderType"
            value: {{ .Values.cloudProviderType }}
          - name: "mapperTopicName"
            value: {{ .Values.mapperTopicName }}
          - name: "targetTopicName"
            value: {{ .Values.targetTopicName }}
          - name: "targetConnectionString"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.storageConnectionSecret }}
                key: TARGET_CONNECTION_STRING
          - name: "targetContainerName"
            value: {{ .Values.targetContainerName }}
          - name: "mapperContainerName"
            value: {{ .Values.mapperContainerName }}
          - name: "bootstrapServer"
            value: {{ .Values.bootstrapServer }}
          - name: "mapperConnectionString"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.storageConnectionSecret }}
                key: MAPPER_CONNECTION_STRING
          - name: "srcConnectionString"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.storageConnectionSecret }}
                key: SRC_CONNECTION_STRING
          - name: "srcContainerName"
            value: {{ .Values.srcContainerName }}
          - name: "AWS_ENDPOINT_URL"
            value: {{ .Values.awsEndpointUrl }}
          - name: "AWS_REGION"
            value: {{ .Values.awsRegion }}
          - name: "AWS_ACCESS_KEY_ID"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.awsAccessSecret }}
                key: AWS_ACCESS_KEY_ID
          - name: "AWS_SECRET_ACCESS_KEY"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.awsAccessSecret }}
                key: AWS_SECRET_ACCESS_KEY
      automountServiceAccountToken: false
