# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Values.configName }}
#   namespace: {{ .Values.namespace }}
#   labels:
#     app: {{ .Values.name }}
#     app.kubernetes.io/managed-by: Helm
#     meta.helm.sh/release-name: {{ .Values.name }}
#     meta.helm.sh/release-namespace: {{ .Values.namespace }}
# data:
#   # PRODUCER_NAME: {{ .Values.producer_name }}
#   SOURCE_NAME: {{ .Values.source_name }}
#   BOOTSTRAP_SERVERS: {{ .Values.bootstrapServer }}
#   TARGET_TOPIC: {{ .Values.target_topic }}
#   STORAGE_ACCOUNT_URL: {{ .Values.storage_account_url }}
#   SOURCE_CONTAINER_NAME: {{ .Values.srcContainerName }}
#   SOURCE_FILE_NAME: {{ .Values.sourceFileName }}
# #  ENV: {{ .Values.env }}
# #  NAME: {{ .Values.name }}
