namespace: ns-dpn-01
name: producer-file-mapper
cloudProviderType: azure
acrName: ""
imageName: producer-file-mapper-eq
imageTag: ""
productType: ""
secretName: eqbd-adaptor-secrets
bootstrapServer: dpn-kafka-src:9092
srcContainerName: eqbd-stage
storageConnectionSecret: producer-file-dp-secret
mapperTopicName: dpn-producer-eqbd-raw
mapperContainerName: eqbd-raw
targetTopicName: dpn-producer-eqbd-target
targetContainerName: eqbd-target
scheduleInterval: 60  # schedule interval in seconds
orgName: EQBD
schemaType: ""

SCHEDULER_BACKEND : kafka-trigger
EXECUTION_MODE: manual
PRODUCT_NAME: eqbd
PIPELINE_CONTROL_TOPIC: dpn-pipeline-control
PIPELINE_STATUS_TOPIC: dpn-pipeline-status
STATSD_HOST: ''
STATSD_PORT : 8125
# ------- AWS Config ------------
awsEndpointUrl: "<<your specific value>>"
awsRegion: us-east-1
awsAccessSecret: aws-access-secret
OTEL_EXPORTER_OTLP_ENDPOINT: dpn-otel-collector.ns-dpn-health-01.svc.cluster.local:4317
OTEL_EXPORTER_OTLP_PROTOCOL: grpc
OTEL_EXPORTER_OTLP_INSECURE: true
SERVICE_NAME: dpn data pipeline
SERVICE_VERSION: 1.0.0
ENVIRONMENT: development