namespace: ns-dpn-01
name: consumer-file-mapper
cloudProviderType: azure
acrName: ""
imageName: consumer-file-mapper
imageTag: ""
bootstrapServer: kafka-target:9092
srcContainerName: dp-consumer-stage
storageConnectionSecret: consumer-file-dp-secret
mapperTopicName: dpn-consumer-extr
mapperContainerName: dp-consumer-trfm
targetTopicName: dpn-consumer-target
targetContainerName: dp-consumer-target
scheduleInterval: 60  # schedule interval in seconds
# ------- AWS Config ------------
awsEndpointUrl: "<<your specific value>>"
awsRegion: us-east-1
awsAccessSecret: aws-access-secret