namespace: ns-dpn-01
name: consumer-file-mapper
cloudProviderType: azure
acrName: ""
imageName: consumer-file-mapper
imageTag: ""
bootstrapServer: dpn-kafka-target:9092
srcContainerName: dp-consumer-stage
storageConnectionSecret: consumer-file-dp-secret
mapperTopicName: dpn-consumer-extr
mapperContainerName: dp-consumer-trfm
targetTopicName: dpn-consumer-target
targetContainerName: dp-consumer-target
scheduleInterval: 60  # schedule interval in seconds

# ------- AWS Config ------------
awsEndpointUrl: "<<your specific value>>"
awsRegion: us-east-1
awsAccessSecret: aws-access-secret

# Scheduler / Execution
SCHEDULER_BACKEND: kafka-trigger
SCHEDULER_BACKEND: manual
replicaCount: 1

# Pipeline Control Topics
PIPELINE_CONTROL_TOPIC: dpn-pipeline-control
PIPELINE_STATUS_TOPIC: dpn-pipeline-status

# Runtime Config
DRAIN_IDLE_SECS: 15
topicTaskTimeoutSecs: 60

# Monitoring
STATSD_PORT: 8125

# OpenTelemetry
SERVICE_NAME: data-pipeline
SERVICE_VERSION: 1.0.0
PRODUCT_NAME: consumer-file

OTEL_EXPORTER_OTLP_ENDPOINT: http://dpn-otel-collector.ns-dpn-health-01.svc.cluster.local:4317
OTEL_EXPORTER_OTLP_PROTOCOL: grpc
OTEL_EXPORTER_OTLP_INSECURE: true
ENVIRONMENT: development