namespace: ns-dpn-01
name: producer-topic-adaptor
acrName: ""
imageName: producer-topic-adaptor
imageTag: ""

bootstrapServer: dpn-kafka-src:9092

# Source topic – mandatory
srcTopicName: dpn-producer-dl-stage

# Leave blank to auto-derive as <srcTopicName>-trfm
mapperTopicName: dpn-producer-dl-raw

srcGroupId: producer-topic-adaptor
consumerRetryDelaySecs: 5

orgName: neso
schemaType: dl
productType: dl
SERVICE_NAME: data-pipeline
SERVICE_VERSION: 1.0.0
 