namespace: ns-dpn-01
name: producer-file-adaptor
cloudProviderType: azure
acrName: ""
imageName: producer-file-adaptor-eq
imageTag: ""
productType: ""
bootstrapServer: dpn-kafka-src:9092
srcContainerName: ssh-stage
storageConnectionSecret: producer-file-dp-secret
mapperTopicName: dpn-producer-ssh-raw
mapperContainerName: ssh-raw
targetTopicName: dpn-producer-ssh-target
targetContainerName: ssh-target
scheduleInterval: 60  # schedule interval in seconds
orgName: SSH
schemaType: ""
STATSD_HOST: ''
STATSD_PORT: 8125
PIPELINE_CONTROL_TOPIC : dpn-pipeline-control
PIPELINE_STATUS_TOPIC : dpn-pipeline-status
SCHEDULER_BACKEND: kafka-trigger
EXECUTION_MODE : manual
PRODUCT_NAME : ssh
# ------- AWS Config ------------
awsEndpointUrl: "<<your specific value>>"
awsRegion: us-east-1
awsAccessSecret: aws-access-secret