namespace: ns-dpn-01
name: producer-file-adaptor
cloudProviderType: azure
acrName: ""
imageName: producer-file-adaptor-eq
imageTag: ""
productType: ""
bootstrapServer: dpn-kafka-src:9092
srcContainerName: eq-stage
storageConnectionSecret: producer-file-dp-secret
mapperTopicName: dpn-producer-eq-raw
mapperContainerName: eq-raw
targetTopicName: dpn-producer-eq-target
targetContainerName: eq-target
scheduleInterval: 60  # schedule interval in seconds
orgName: EQ
schemaType: ""
STATSD_HOST: ''
STATSD_PORT: 8125
PIPELINE_CONTROL_TOPIC : dpn-pipeline-control
PIPELINE_STATUS_TOPIC : dpn-pipeline-status
SCHEDULER_BACKEND: kafka-trigger
EXECUTION_MODE : manual
PRODUCT_NAME : eq
# ------- AWS Config ------------
awsEndpointUrl: "<<your specific value>>"
awsRegion: us-east-1
awsAccessSecret: aws-access-secret