namespace: ns-dpn-01
name: producer-file-adaptor
cloudProviderType: azure
acrName: ""
imageName: producer-file-adaptor-eq
imageTag: ""
productType: ""
bootstrapServer: kafka-src:9092
srcContainerName: bp-natural-gas-stage
storageConnectionSecret: producer-file-dp-secret
mapperTopicName: dpn-producer-bp-natural-gas-raw
mapperContainerName: bp-natural-gas-raw
targetTopicName: dpn-producer-bp-natural-gas-target
targetContainerName: bp-natural-gas-target
scheduleInterval: 60  # schedule interval in seconds
orgName: BP
schemaType: ""
# ------- AWS Config ------------
awsEndpointUrl: "<<your specific value>>"
awsRegion: us-east-1
awsAccessSecret: aws-access-secret