{{- if .Values.kafkaOauthClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kafkaOauthSecretName | default (printf "%s-kafka-oauth" .Values.name) }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  client-secret: {{ .Values.kafkaOauthClientSecret | quote }}
{{- end }}
